import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";


const poppins = Poppins({

  subsets: ["latin"],
  weight: ["600", "500", "400", "300"]
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${poppins.className} antialiased`}
      >         
      <Navbar/>
        <main className="mx-10 mt-5">
 
          {children}
        </main>

      </body>
    </html>
  );
}
